### PR TITLE
use wx.TheClipboard for copying features between two instances

### PR DESCRIPTION
**Pull request by openpaul**
I just implemented the use of wx.TheClipboard. This enables to store different types of content between applications.

So I made a text copy of the dna the standart. It gets pasted whenever someone copys from DNApy to gedit or somewhere else.
If you paste from DNApy to DNApy it will instead try to use a different content I  called "application/DNApy". It is the same object as the self.clipboard instance you used before.

The functions RichCopy and RichPaste handle the operations.

Take a look at the code, I think it is a rather small change to the previous state.

I now will try to make selection more powerfull, to allow selections with start>finish in circular dna.

### CODE REVIEW

**Comment by 0b0bby0** [comment]
That's great! This feature was sorely needed. I've been modifying the user interface so that the DNA sequence and the plasmid view are visible at the same time. It's almost done, I just need to fix a few issues with one window updating the other and then I'll merge it all together.

**Comment by openpaul** [comment]
That sounds good. I am looking foreward to this.

**Comment by 0b0bby0** [comment]
The pasting isn't working right. Is it working ok for you? For instance, if I want to paste the reverse complement it does not work. Also, pasting to a new file only works if there is already a feature. Shall I look into this or will you?

**Comment by openpaul** [comment]
Oh, hmmm... thats embarrassing. I should find time to look into this this week. Will update this commit as soon as it is fixed.

**Comment by openpaul** [comment]
It looks like pasting features in another window only works if there is already a genebank file loaded. Else I get the error:
```python main.py 
Traceback (most recent call last):
  File "main.py", line 490, in paste
    self.DNApy.dnaview.paste()		
  File "/home/paul/Seafile/Webseiten_Software/2014/2014 dnapy/DNApy/dnaeditor_GUI.py", line 609, in paste
    genbank.gb.RichPaste(start)
  File "/home/paul/Seafile/Webseiten_Software/2014/2014 dnapy/DNApy/genbank.py", line 1024, in RichPaste
    self.paste_feature(pasteDNA['features'][i], ip-1)
  File "/home/paul/Seafile/Webseiten_Software/2014/2014 dnapy/DNApy/genbank.py", line 1043, in paste_feature
    self.gbfile['features'].append(feature)
AttributeError: 'NoneType' object has no attribute 'append'
```

This could be fixed if DNApy would initialise the variable *self.gbfile['features'].append(feature)* at startup. As I am not familiar with the code there I do not know what to do. Can you help me out here?

I added code to also make reverse complement copy and cutting possible. It wokrs alright I think.
But I stumbled upon another bug: Features do not always get copied. as I reused your code I maybe have introduced this bug, but I will have to look into that further.

**Pull request merged**
