### PR TITLE
Changed order of ok and cancel to cancel|ok

### PR DESCRIPTION
**Pull request by openpaul**
As discussed I have changed the order of the dialogue to have the order cancel|ok.

### CODE REVIEW

**Comment by openpaul** [comment]
Ok, now this changed into a major request...

I somehow changed tonight all the code for enzyme-selection to now use a new class called restrictionEnzyme.

This enables the software to store more info about the enzymes and update the info continiusly.
It is now also possible to retrive at everytime every restrictionsite from the element "self.restrictionEnzyme" in main.py.

This way a user could show restrictionenzymes in the plasmid map based on a certain selection for example.

The function of the software is the same and the coloring in the dna-editor works as previously.

**Comment by openpaul** [comment]
Ok, now the digestion works again, and it gets updated on the run:

- open a file --> loads all enzymes and find every restriction site
- select enzymes --> creates list of objects with every info
- digest --> show the gel
- change some bases, delet or insert --> updates every restriction site
- show digest again --> updated view

I guess thats cool. Even if this can't be merged automatically, I will implement this again or resolve the merge conflicts.

**Comment by 0b0bby0** [comment]
That sounds pretty cool. Looking forward to trying it out. I'm having some problems making the updates work between the different panels. The problem is that each panel functions on its own and is unaware of the others. When I change something in one panel it needs to tell the others to update. I need some sort of dispatcher to send messages to update the other two panels. I already made some bad experiences with PubSub and I'm not sure which one to pick. Do you have any experience?

**Comment by openpaul** [comment]
hmm.... yes. Right now you update the view whenever a panel is changed, right?
This software is my first GUI, so I really have no experience at all with that kind of code.

I suppose one would have to calll the update() (http://www.wxpython.org/docs/api/wx.Window-class.html#Update) method for each panel manually every time it has to update.
How did you split the window for now? Using MultiSplitterWindow or how did you accomplish that?

I guess it would be possible to store the panels in some variables like self.panels[panel1] and then call a update function like
'''
def updatePanels(self, numberOfPanel=all):
    if numberOfPanel == "all":
        # call update for all pannels 
    else:
        if numberOfPanel == 1:
             # only update the first annel etc,
              self.panels[panel1].update()
''' 
Could something like that work?

**Comment by 0b0bby0** [comment]
Well, all the tabs are gone now. Since the sequence view and plasmid view will always be visible that just leaves the genbank view and I will change that to a popup window instead. Removing the tabs frees up a good half inch of vertical space across the screen.

But the tricky bit is not to update each of the panels from main.py. The tricky thing is for an event in one of the panels (for example a click in the plasmid view) to result in the other two panels being updated. I had this hard-coded with soeme wierd GetParent().GetParent().update_ownUI() construct. But this is not flexible. 

I think I have found a solution with wx.PostEvent. I'll try that out tomorrow.

**Comment by 0b0bby0** [comment]
Conflicts resolved and branch mergeged.

**Comment by openpaul** [comment]
OK, cool. Will test it soon.

**Pull request merged**
