### PR TITLE
New plasmid view

### PR DESCRIPTION
**Pull request by openpaul**
So, this is the new plasmid GUI I've written.

It uses Pycairo (http://cairographics.org/documentation/pycairo/2/) for drawing. 

As of now it only draws two circles representing the two DNA strands. Also it draws features as arrows. Reverse features are iside, 5'-3' are outside of the plasmid.

Adding labels to the plasmid can be done in the function drawCairoLabels on line 744. For calculating label positions I prepared the function labelPositions on line 906 (Both in plasmid_GUI.py).

I suppose drawing the labels should happen before drawing the features, as only than the arrows can be on top of the lines. This would require some reordering of code.

I put dummy code into drawCairoLabels() to draw lines for features without labels:

dummy

I changed some colors, as I liked them better this way. Feel free to ignore those changes.

### CODE REVIEW

**Comment by openpaul** [comment]
I added "export plasmid map" to the file menu and fixed a bug when canceling while opening a file would still open that file.

**Comment by 0b0bby0** [comment]
Cool I've merged this in now. There seems to be some new bugs that I'll iron out before I do the labels. The one's I've seen so far is that DNA selection made in the sequence view does not appear on the plasmid. Also when one feature is selected on the plasmid and another is moused over, that mouse over highlight stays after the pointer have moved off. Those should not be too hard to fix though.

**Comment by 0b0bby0** [comment]
Ah, also, the copy paste stuff still does not seem to work for me. When copying the reverse complement or pasting the reverse complement the features go missing. Could you look into that?

**Comment by openpaul** [comment]
hmm... this copying really should work. And I will see what I can do. 
I also found that, at least on my screen, moving the split screen with cairo plasmid view results in a flickering image troughout the DNApy. I do not have any idea if this is just me or how I could have caused this. Can you reproduce this?

**Comment by openpaul** [comment]
Hmm... so I am just fixing the copy/pasting issue and I do not know if I did it correct. 

Now it behaves like:
copy of  CGAT:
paste: CGAT
rev comp paste: ATCG (features reversed)

rev comp copy of CGAT:
paste: ATCG (features reversed)
rev com past: CGAT

I guess this is how it is suppose to work, is it?

**Comment by 0b0bby0** [comment]
That is how it should work. Iäll give it a try!

**Pull request merged**
